/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/El3elrcSTXS
 */
import Link from "next/link"

export function LawnCare() {
  return (
    <section key="1" className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 lg:grid-cols-1 xl:grid-cols-1">
          <section className="flex flex-col lg:flex-row items-center space-y-4 lg:space-y-0 lg:space-x-4 w-full">
            <TractorIcon className="h-12 w-12" />
            <div>
              <h3 className="text-2xl font-bold">Lawn Care</h3>
              <p className="text-gray-500 md:text-lg dark:text-gray-400">
                We provide professional lawn care services to keep your yard looking its best.
              </p>
            </div>
          </section>
        </div>

        <section key="2" className="w-full py-12 md:py-24 lg:py-32">
        
        </section>

        <section key="3" className="w-full py-12 md:py-24 lg:py-32">
        <div className="grid gap-6 lg:grid-cols-1 xl:grid-cols-1">
          <section className="flex flex-col lg:flex-row items-center space-y-4 lg:space-y-0 lg:space-x-4 w-full">
            <FlowerIcon className="h-12 w-12" />
            <div>
            <h3 className="text-xl font-bold">Garden Design</h3>
              <p className="text-gray-500 md:text-base dark:text-gray-400">
                  Our expert designers can create a beautiful and functional garden space tailored to your needs.
              </p>
            </div>
          </section>
        </div>
        <div className="grid gap-6 lg:grid-cols-1 xl:grid-cols-1">
          <section className="flex flex-col lg:flex-row items-center space-y-4 lg:space-y-0 lg:space-x-4 w-full">
            <CropIcon className="h-12 w-12" />
            <div>
            <h3 className="text-xl font-bold">Irrigation System Installation</h3>
                <p className="text-gray-500 md:text-base dark:text-gray-400">
                  We install efficient irrigation systems to ensure your plants get the right amount of water.
                </p>
              </div>
          </section>
        </div>

      </section>
      <div className="fixed right-4 bottom-4 md:right-8 md:bottom-8">
        <Link
          href="/Contact"
          className="inline-block py-3 px-6 text-black bg-orange-400 rounded-md shadow-lg hover:bg-gray-700 focus-visible:ring-2 focus-visible:ring-gray-600 focus-visible:ring-opacity-50"
        
          style={{ backgroundColor: "#ff9900", 
                  textDecorationColor: "black"}}>
          Get a Free Quote
        </Link>
      </div>
    </div>
    </section>
  )
}


function TractorIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 4h9l1 7" />
      <path d="M4 11V4" />
      <path d="M8 10V4" />
      <path d="M18 5c-.6 0-1 .4-1 1v5.6" />
      <path d="m10 11 .9c.6 0 .9.5.8 1.1l-.8 5h-1" />
      <circle cx="7" cy="15" r=".5" />
      <circle cx="7" cy="15" r="5" />
      <path d="M16 18h-5" />
      <circle cx="18" cy="18" r="2" />
    </svg>
  )
}


function FlowerIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 7.5a4.5 4.5 0 1 4.5M12 7.5A4.5 7.5 12M12 7.5V9m-4.5 3a4.5 4.5M7.5 12H9m7.5 0a4.5 1-4.5 4.5m4.5-4.5H15m-3 4.5V15" />
      <circle cx="12" cy="12" r="3" />
      <path d="m8 16 1.5-1.5" />
      <path d="M14.5 9.5 16 8" />
      <path d="m8 8 1.5" />
      <path d="M14.5 14.5 16" />
    </svg>
  )
}


function CropIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 2v14a2 2 0 2h14" />
      <path d="M18 22V8a2 2 0 0-2-2H2" />
    </svg>
  )
}
